"""empty message

Revision ID: 08f4e8055893
Revises: d74ea0d2c946
Create Date: 2023-06-30 10:08:15.528992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f4e8055893'
down_revision = 'd74ea0d2c946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qteamevent2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qteamevent2', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
