"""empty message

Revision ID: 1ed6ae7e0f8d
Revises: 08f4e8055893
Create Date: 2023-08-30 16:47:05.215115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed6ae7e0f8d'
down_revision = '08f4e8055893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vwcupevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('q1', sa.String(), nullable=False),
    sa.Column('q2', sa.String(), nullable=False),
    sa.Column('how_many_people', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vwcupevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vwcupevent_created'), ['created'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vwcupevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vwcupevent_created'))

    op.drop_table('vwcupevent')
    # ### end Alembic commands ###
