"""empty message

Revision ID: 296120bd5a65
Revises: 7e38e9d439d7
Create Date: 2023-05-05 14:20:32.316587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296120bd5a65'
down_revision = '7e38e9d439d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suzuki_lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suzuki_lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('created')

    # ### end Alembic commands ###
