"""empty message

Revision ID: 440dff46dcc0
Revises: a998199e4644
Create Date: 2023-05-03 17:22:19.039757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440dff46dcc0'
down_revision = 'a998199e4644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qteamevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('how_many_centers', sa.String(), nullable=False),
    sa.Column('which_type_car', sa.String(), nullable=False),
    sa.Column('when_summer_tires', sa.String(), nullable=False),
    sa.Column('how_many_people', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qteamevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qteamevent_created'), ['created'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_created')

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('how_many_centers', sa.VARCHAR(), nullable=False),
    sa.Column('which_type_car', sa.VARCHAR(), nullable=False),
    sa.Column('when_summer_tires', sa.VARCHAR(), nullable=False),
    sa.Column('how_many_people', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_created', ['created'], unique=False)

    with op.batch_alter_table('qteamevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qteamevent_created'))

    op.drop_table('qteamevent')
    # ### end Alembic commands ###
