"""empty message

Revision ID: 4e6567c826c4
Revises: 1ed6ae7e0f8d
Create Date: 2023-08-31 09:02:26.897047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6567c826c4'
down_revision = '1ed6ae7e0f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vwcupevent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postal_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vwcupevent', schema=None) as batch_op:
        batch_op.drop_column('dob')
        batch_op.drop_column('postal_code')

    # ### end Alembic commands ###
