"""empty message

Revision ID: 91cde7dfd805
Revises: 296120bd5a65
Create Date: 2023-05-05 17:02:23.831402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91cde7dfd805'
down_revision = '296120bd5a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suzuki_lead', schema=None) as batch_op:
        batch_op.drop_column('salutation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suzuki_lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salutation', sa.VARCHAR(length=10), nullable=False))

    # ### end Alembic commands ###
