"""empty message

Revision ID: cae99fdfb3bb
Revises: f46eab0f2cbf
Create Date: 2023-06-02 10:59:25.252274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae99fdfb3bb'
down_revision = 'f46eab0f2cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fordbroncoevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_generation', sa.String(), nullable=False),
    sa.Column('goat_meaning', sa.String(), nullable=False),
    sa.Column('famous_person', sa.String(), nullable=False),
    sa.Column('how_old', sa.String(), nullable=False),
    sa.Column('towing_capacity', sa.String(), nullable=False),
    sa.Column('total_gears', sa.String(), nullable=False),
    sa.Column('how_many_people', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fordbroncoevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fordbroncoevent_created'), ['created'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fordbroncoevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fordbroncoevent_created'))

    op.drop_table('fordbroncoevent')
    # ### end Alembic commands ###
