"""empty message

Revision ID: f46eab0f2cbf
Revises: 91cde7dfd805
Create Date: 2023-05-06 15:03:03.394782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46eab0f2cbf'
down_revision = '91cde7dfd805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qteamevent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locale', sa.String(length=10), nullable=True))

    with op.batch_alter_table('suzuki_lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locale', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suzuki_lead', schema=None) as batch_op:
        batch_op.drop_column('locale')

    with op.batch_alter_table('qteamevent', schema=None) as batch_op:
        batch_op.drop_column('locale')

    # ### end Alembic commands ###
